#!/bin/bash 
#PBS -N zip_files-10-17-16
#PBS -q astro_prod
#PBS -l nodes=1:ppn=1,mem=16gb
#PBS -l walltime=12:00:00
#PBS -j oe
#PBS -m abe
#PBS -M duncan.campbell@yale.edu

# Switch to the working directory; by default PBS launches processes
# from your home directory.
echo Working directory is $PBS_O_WORKDIR
cd /home/fas/padmanabhan/dac29/scratch/data/Bolshoi/trees

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`

# Run your job
./zip_files_2.sh
